# 1. Hasil evaluasi kelengkapan data

# Farms

| Column   | Description                  |
|----------|------------------------------|
| `id`     | ID Farm                      |
| `province` | Lokasi tambak (provinsi)   |
| `regency` | Lokasi tambak (regency)     |
| `timezone` | Timezone tambak            |


# Ponds

| Column   | Description                  |
|----------|------------------------------|
| `id`     | ID Kolam                     |
| `length` | Panjang kolam (m)            |
| `width`  | Lebar kolam (m)              |
| `deep`   | Kedalaman kolam (m)          |
| `farm_id` | Foreign key to farms(id)    |


# Cycles

| Column       | Description                       |
|--------------|-----------------------------------|
| `id`         | ID Siklus                         |
| `started_at` | Tanggal siklus dimulai            |
| `finished_at` | Tanggal siklus selesai           |
| `total_seed` | Jumlah benur yang ditebar (ekor)  |
| `area`       | Luas area kolam (m²)              |
| `pond_id`    | Foreign key to ponds(id)          |

# Feeds

| Column     | Description                        |
|------------|------------------------------------|
| `cycle_id` | Foreign key to cycles(id)          |
| `logged_at` | Waktu pemberian pakan (UTC)       |
| `quantity` | Jumlah pakan yang diberikan (kg)   |


# Fasting

| Column      | Description                   |
|-------------|-------------------------------|
| `cycle_id`  | Foreign key to cycles(id)     |
| `logged_date` | Tanggal Puasa               |
| `fasting`   | Puasa/Tidak (boolean)         |


# Harvests

| Column       | Description                           |
|--------------|---------------------------------------|
| `cycle_id`   | Foreign key to cycles(id)             |
| `harvested_at` | Tanggal Panen                       |
| `status`     | Status panen                          |
| `size`       | Ukuran udang yang dipanen (ekor/kg)   |
| `weight`     | Berat panen (kg)                      |

# Sampling

| Column          | Description                      |
|-----------------|----------------------------------|
| `cycle_id`      | Foreign key to cycles(id)        |
| `sampled_at`    | Tanggal Sampling                 |
| `average_weight` | Rerata berat udang (gr)         |

# Measurements

| Column                | Description                                  |
|-----------------------|----------------------------------------------|
| `cycle_id`            | Foreign key to cycles(id)                    |
| `measured_at`         | Tanggal Pengukuran                           |
| `morning_temperature` | Water temperature in the morning (Celcius)   |
| `evening_temperature` | Water temperature in the evening (Celcius)   |
| `morning_do`          | Dissolved oxygen in the morning (ppm)        |
| `evening_do`          | Dissolved oxygen in the evening (ppm)        |
| `morning_salinity`    | Salinity in the morning (ppt)                |
| `evening_salinity`    | Salinity in the evening (ppt)                |
| `morning_pH`          | pH in the morning (mole/litre)               |
| `evening_pH`          | pH in the evening (mole/litre)               |
| `transparency`        | Transparency (cm)                            |
| `ammonia`             | Ammonia concentration (ppm)                  |
| `nitrate`             | Nitrate concentration (ppm)                  |
| `nitrite`             | Nitrite concentration (ppm)                  |
| `alkalinity`          | Alkalinity concentration (ppm)               |
| `hardness`            | Hardness concentration (ppm)                 |
| `calcium`             | Calcium concentration (ppm)                  |
| `magnesium`           | Magnesium concentration (ppm)                |
| `carbonate`           | Carbonate concentration (ppm)                |
| `bicarbonate`         | Bicarbonate concentration (ppm)              |
| `tom`                 | TOM concentration (ppm)                      |
| `total_plankton`      | Total plankton concentration                 |


# Feed Tray

| Column Name | Description |
|---|---|
| cycle_id | Foreign key to cycles (id) |
| quantity | Jumlah estimasi populasi udang yang mati (ekor) |
| logged_at | Tanggal dan waktu data feed tray/anco dicatatkan |
| feed_logged_at | Tanggal dan waktu pemberian pakan dicatatkan |
| tray_number | Nomor anco, dalam satu kolam bisa terdiri dari satu hingga empat anco |
| feed_remaining_percent | Jumlah sisa pakan yang tersisa di anco (%) |
| remark | Catatan terkait kondisi anco atau pun perilaku konsumsi pakan dari udang |


# Mortalities

| Column Name | Description |
|---|---|
| cycle_id | Foreign key to cycles (id) |
| quantity | Jumlah estimasi populasi udang yang mati (ekor) |
| recorded_at | Tanggal data mortality dicatatkan |
| average_weight | Rerata bobot udang (ABW) saat pencatatan kematian (g) |


In [61]:
import pandas as pd

# Membaca data dari file CSV untuk setiap tabel dalam folder "Data"
cycles = pd.read_csv('Data/cycles.csv')
farms = pd.read_csv('Data/farms.csv')
fasting = pd.read_csv('Data/fasting.csv')
fastings = pd.read_csv('Data/fastings.csv')
feed_tray = pd.read_csv('Data/feed_tray.csv')
feeds = pd.read_csv('Data/feeds.csv')
harvests = pd.read_csv('Data/harvests.csv')
measurements = pd.read_csv('Data/measurements.csv')
mortalities = pd.read_csv('Data/mortalities.csv')
ponds = pd.read_csv('Data/ponds.csv')
samplings = pd.read_csv('Data/samplings.csv')

# Cycles

In [62]:
# sanity check
cycles

id  pond_id  species_id  total_seed               started_at  \
0     18876    36294         1.0      331920  2022-10-14 00:00:00.000   
1     22118    37102         1.0       40000  2023-04-26 00:00:00.000   
2     24088    39154         NaN      357570  2023-08-01 00:00:00.000   
3     17743    20914         1.0      168275  2022-07-19 00:00:00.000   
4     17125    34187         1.0      188000  2022-07-07 00:00:00.000   
...     ...      ...         ...         ...                      ...   
2612  19131    34712         2.0      300000  2022-10-25 00:00:00.000   
2613  27552    45697         1.0      100000  2023-11-05 00:00:00.000   
2614  27885    24570         1.0       30716  2023-12-02 00:00:00.000   
2615  15868    32398         1.0      150000  2022-04-28 00:00:00.000   
2616  20849    35913         1.0      384000  2023-02-09 00:00:00.000   

                  finished_at                  remark  \
0     2023-01-29 00:00:00.000                     NaN   
1     2023-06-23 00:00:00.000                  #TBR01   
2     2023-10-18 00:00:00.000             #SiklusFarm   
3     2022-09-29 00:00:00.000  #SiklusCustomerPermadi   
4     2022-09-20 00:00:00.000            #SiklusTebar   
...                       ...                     ...   
2612  2023-01-21 00:00:00.000                     NaN   
2613  2024-02-13 00:00:00.000                  #TBR03   
2614  2024-02-29 00:00:00.000                  #TBR05   
2615  2022-06-21 00:00:00.000            #SiklusTebar   
2616  2023-04-07 00:00:00.000                     NaN   

                   created_at               updated_at    area  ...  \
0     2022-10-14 12:34:23.000  2023-01-30 01:46:27.000  4030.0  ...   
1     2023-04-30 22:28:13.000  2023-06-26 05:35:32.000   399.0  ...   
2     2023-07-12 01:13:05.000  2023-10-19 04:23:11.000  2000.0  ...   
3     2022-08-14 04:40:46.000  2022-10-06 00:09:36.000  1512.0  ...   
4     2022-07-12 00:24:30.000  2022-10-15 04:27:24.000  1225.0  ...   
...                       ...                      ...     ...  ...   
2612  2022-10-25 10:13:31.000  2023-01-25 08:01:19.000  4999.9  ...   
2613  2023-11-18 03:43:40.000  2024-03-27 02:52:36.000   900.0  ...   
2614  2023-12-03 03:06:01.000  2024-03-03 03:03:26.000    86.0  ...   
2615  2022-05-08 16:02:51.000  2022-08-23 03:12:20.000  1600.0  ...   
2616  2023-02-14 00:23:40.000  2023-04-14 00:04:22.000  2915.0  ...   

                 extracted_at  subscription_type               ordered_at  \
0     2024-04-12 17:02:22.000               Free                      NaN   
1     2024-04-12 17:02:22.000               Free                      NaN   
2     2024-04-12 17:02:22.000               Free  2023-07-12 01:13:05.000   
3     2024-04-12 17:02:22.000               Free                      NaN   
4     2024-04-12 17:02:22.000               Free  2022-07-12 00:24:30.000   
...                       ...                ...                      ...   
2612  2024-04-12 17:02:22.000               Free                      NaN   
2613  2024-04-12 17:02:22.000               Free  2023-11-18 03:43:40.000   
2614  2024-04-12 17:02:22.000               Free                      NaN   
2615  2024-04-12 17:02:22.000               Free  2022-05-08 16:02:51.000   
2616  2024-04-12 17:02:22.000               Free                      NaN   

      hatchery_id total_seed_type  \
0            66.0             net   
1            83.0             net   
2          1004.0           gross   
3             3.0          actual   
4            35.0             net   
...           ...             ...   
2612       1020.0          actual   
2613       1022.0             net   
2614         83.0           gross   
2615         35.0           gross   
2616         83.0          actual   

                                     hatchery_name pond_name  pond_length  \
0                             UD. Benur Ndaru Laut         H        65.00   
1                                    CV Raja Benur        A1        30

In [63]:
# Check basic information about the dataframe
print("Basic Information:")
cycles.info()

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2617 entries, 0 to 2616
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   id                      2617 non-null   int64  
 1   pond_id                 2617 non-null   int64  
 2   species_id              1803 non-null   float64
 3   total_seed              2617 non-null   int64  
 4   started_at              2617 non-null   object 
 5   finished_at             2616 non-null   object 
 6   remark                  1336 non-null   object 
 7   created_at              2617 non-null   object 
 8   updated_at              2617 non-null   object 
 9   area                    2617 non-null   float64
 10  initial_age             2569 non-null   float64
 11  limit_weight_per_area   2610 non-null   float64
 12  target_cultivation_day  2614 non-null   float64
 13  target_size             2613 non-null   float64
 14  extracted_at         

In [64]:
# Check for missing values
print("\nMissing Values:")
print(cycles.isnull().sum())


Missing Values:
id                           0
pond_id                      0
species_id                 814
total_seed                   0
started_at                   0
finished_at                  1
remark                    1281
created_at                   0
updated_at                   0
area                         0
initial_age                 48
limit_weight_per_area        7
target_cultivation_day       3
target_size                  4
extracted_at                 0
subscription_type            0
ordered_at                1523
hatchery_id                465
total_seed_type            242
hatchery_name              465
pond_name                    0
pond_length                  6
pond_width                   6
pond_depth                 118
dtype: int64


In [65]:
# Check unique values for object columns
object_columns = cycles.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(cycles[column].unique())


Unique values for started_at:
['2022-10-14 00:00:00.000' '2023-04-26 00:00:00.000'
 '2023-08-01 00:00:00.000' '2022-07-19 00:00:00.000'
 '2022-07-07 00:00:00.000' '2023-12-20 00:00:00.000'
 '2023-10-02 00:00:00.000' '2023-07-19 00:00:00.000'
 '2023-07-08 00:00:00.000' '2023-09-13 00:00:00.000'
 '2021-05-20 00:00:00.000' '2021-09-30 00:00:00.000'
 '2022-08-14 00:00:00.000' '2023-07-29 00:00:00.000'
 '2023-01-25 00:00:00.000' '2023-08-04 00:00:00.000'
 '2023-08-20 00:00:00.000' '2023-06-17 00:00:00.000'
 '2023-04-07 00:00:00.000' '2021-09-08 00:00:00.000'
 '2023-10-04 00:00:00.000' '2023-12-05 00:00:00.000'
 '2023-02-14 00:00:00.000' '2021-04-10 00:00:00.000'
 '2021-07-22 00:00:00.000' '2022-05-22 00:00:00.000'
 '2021-06-16 00:00:00.000' '2021-07-11 00:00:00.000'
 '2022-06-24 00:00:00.000' '2022-10-21 00:00:00.000'
 '2023-09-21 00:00:00.000' '2020-08-11 00:00:00.000'
 '2021-01-27 00:00:00.000' '2024-01-22 00:00:00.000'
 '2021-12-20 00:00:00.000' '2023-12-04 00:00:00.000'
 '2022-09-26 00

In [66]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
cycles.describe()


Descriptive Statistics:


id       pond_id   species_id    total_seed           area  \
count   2617.000000   2617.000000  1803.000000  2.617000e+03    2617.000000   
mean   19900.667176  32218.568972     1.113699  2.197552e+05    2292.673653   
std     6006.802428  10156.254276     0.317534  1.710980e+05   12104.748470   
min     3458.000000      1.000000     1.000000  1.000000e+01       1.020000   
25%    16091.000000  24570.000000     1.000000  9.600000e+04     810.000000   
50%    20401.000000  34697.000000     1.000000  1.943920e+05    1400.000000   
75%    24804.000000  38943.000000     1.000000  3.000000e+05    2358.000000   
max    29874.000000  47282.000000     2.000000  1.800000e+06  422500.000000   

       initial_age  limit_weight_per_area  target_cultivation_day  \
count  2569.000000            2610.000000             2614.000000   
mean      0.704944               1.559452              112.591813   
std       4.744826               6.640846               23.564663   
min       0.000000               0.600000                0.000000   
25%       0.000000               1.250000              100.000000   
50%       0.000000               1.250000              120.000000   
75%       0.000000               1.250000              120.000000   
max      75.000000             270.000000              348.000000   

       target_size  hatchery_id  pond_length   pond_width   pond_depth  
count  2613.000000  2152.000000  2611.000000  2611.000000  2499.000000  
mean     52.696135   412.304368    44.169694    36.299874     4.207935  
std      22.803397   472.518010    26.640087    23.034006    19.647010  
min       0.000000     1.000000     3.000000     1.500000     0.600000  
25%      45.000000    35.000000    30.000000    26.230000     1.000000  
50%      55.000000    83.000000    40.000000    34.500000     1.300000  
75%      55.000000  1004.000000    53.000000    44.720000     1.500000  
max    1000.000000  1077.000000   650.000000   650.000000   300.000000

In [67]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
cycles.duplicated().sum()


Duplicate Rows:


50

In [68]:
# Range Validation for Integer and Float Columns
numeric_columns = cycles.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = cycles[column].min()
    max_value = cycles[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")


Range for id: 3458 to 29874

Range for pond_id: 1 to 47282

Range for species_id: 1.0 to 2.0

Range for total_seed: 10 to 1800000

Range for area: 1.02 to 422500.0

Range for initial_age: 0.0 to 75.0

Range for limit_weight_per_area: 0.6 to 270.0

Range for target_cultivation_day: 0.0 to 348.0

Range for target_size: 0.0 to 1000.0

Range for hatchery_id: 1.0 to 1077.0

Range for pond_length: 3.0 to 650.0

Range for pond_width: 1.5 to 650.0

Range for pond_depth: 0.6 to 300.0


In [69]:
# Foreign Key Validation
# Check if all 'pond_id' values exist in the 'ponds' table
invalid_pond_ids = cycles[~cycles['pond_id'].isin(ponds['id'])]
print("\nInvalid 'pond_id' values:")
print(invalid_pond_ids)


Invalid 'pond_id' values:
         id  pond_id  species_id  total_seed               started_at  \
0     18876    36294         1.0      331920  2022-10-14 00:00:00.000   
1     22118    37102         1.0       40000  2023-04-26 00:00:00.000   
2     24088    39154         NaN      357570  2023-08-01 00:00:00.000   
3     17743    20914         1.0      168275  2022-07-19 00:00:00.000   
4     17125    34187         1.0      188000  2022-07-07 00:00:00.000   
...     ...      ...         ...         ...                      ...   
2612  19131    34712         2.0      300000  2022-10-25 00:00:00.000   
2613  27552    45697         1.0      100000  2023-11-05 00:00:00.000   
2614  27885    24570         1.0       30716  2023-12-02 00:00:00.000   
2615  15868    32398         1.0      150000  2022-04-28 00:00:00.000   
2616  20849    35913         1.0      384000  2023-02-09 00:00:00.000   

                  finished_at                  remark  \
0     2023-01-29 00:00:00.000          

In [70]:
# Columns with missing values
columns_with_missing = cycles.columns[cycles.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(cycles.loc[cycles[column].isnull()])
    print("\n")

Missing values in column 'species_id':
         id  pond_id  species_id  total_seed               started_at  \
2     24088    39154         NaN      357570  2023-08-01 00:00:00.000   
5     28070    46261         NaN      200128  2023-12-20 00:00:00.000   
8     24702    34746         NaN      439635  2023-07-19 00:00:00.000   
16    24542    41484         NaN      516780  2023-08-04 00:00:00.000   
22    28280    41859         NaN      237300  2023-12-05 00:00:00.000   
...     ...      ...         ...         ...                      ...   
2597  23106    41216         NaN      985776  2023-03-15 00:00:00.000   
2603  18872    36246         NaN      130000  2022-10-11 00:00:00.000   
2604  25138    43244         NaN      436424  2023-08-21 00:00:00.000   
2607  17449    34490         NaN      380000  2022-07-02 00:00:00.000   
2608  19614    33945         NaN      400000  2022-12-01 00:00:00.000   

                  finished_at            remark               created_at  \
2     20

### Summary of Data Validation for `cycles` Table

**Basic Information:**
- The dataset contains 2617 entries with 24 columns.
- Data types include integers, floats, and objects (strings/dates).

**Missing Values:**
- Significant columns with missing values:
  - `species_id`: 814 missing
  - `finished_at`: 1 missing
  - `remark`: 1281 missing
  - `initial_age`: 48 missing
  - `limit_weight_per_area`: 7 missing
  - `target_cultivation_day`: 3 missing
  - `target_size`: 4 missing
  - `ordered_at`: 1523 missing
  - `hatchery_id`: 465 missing
  - `total_seed_type`: 242 missing
  - `hatchery_name`: 465 missing
  - `pond_length`: 6 missing
  - `pond_width`: 6 missing
  - `pond_depth`: 118 missing

**Descriptive Statistics:**
- `id` ranges from 3458 to 29874.
- `pond_id` ranges from 1 to 47282.
- `species_id` ranges from 1.0 to 2.0.
- `total_seed` ranges from 10 to 1800000.
- `area` ranges from 1.02 to 422500.0.
- `initial_age` ranges from 0.0 to 75.0.
- `limit_weight_per_area` ranges from 0.6 to 270.0.
- `target_cultivation_day` ranges from 0.0 to 348.0.
- `target_size` ranges from 0.0 to 1000.0.
- `hatchery_id` ranges from 1.0 to 1077.0.
- `pond_length` ranges from 3.0 to 650.0.
- `pond_width` ranges from 1.5 to 650.0.
- `pond_depth` ranges from 0.6 to 300.0.

**Duplicate Rows:**
- There are 50 duplicate rows in the dataset.

**Observations:**
1. **Missing Values:**
   - Several columns have a significant number of missing values, especially `remark`, `ordered_at`, and `species_id`.
   - These missing values need to be addressed, possibly through imputation or removal, depending on the use case.

2. **Duplicate Rows:**
   - The presence of 50 duplicate rows suggests a need for data cleaning to ensure data integrity.

3. **Range Validations:**
   - The ranges for each numeric column seem reasonable, except for potentially extreme values in columns like `total_seed`, `area`, and `target_size`. These should be further examined to confirm their validity.

4. **Data Types:**
   - Ensure the date columns (`started_at`, `finished_at`, etc.) are in the correct datetime format for further analysis.

5. **Foreign Key Validation:**
   - Check if all `pond_id` values exist in the `ponds` table to ensure referential integrity.

### Actions Recommended:
1. **Handle Missing Values:**
   - Impute or remove missing values based on the column's importance and data availability.
   - For critical columns, consider using median or mean for numerical imputation or mode for categorical.

2. **Remove Duplicates:**
   - Remove duplicate rows to maintain data integrity.

3. **Range Check and Outlier Detection:**
   - Investigate extreme values in key columns like `total_seed`, `area`, and `target_size` to determine if they are valid or require correction.

4. **Data Type Conversion:**
   - Convert date columns to `datetime` format for accurate time-based analysis.

5. **Foreign Key Integrity:**
   - Ensure all `pond_id` values exist in the `ponds` table to maintain database integrity.

## Farms Table Analysis

In [71]:
# sanity check
farms

id           province      regency timezone
0      652         JAWA BARAT       SUBANG   +07:00
1      869   SULAWESI SELATAN        BARRU   +08:00
2      900         JAWA TIMUR      PACITAN   +07:00
3     1000         JAWA TIMUR    SITUBONDO   +07:00
4     1106         JAWA TIMUR   BANYUWANGI   +07:00
..     ...                ...          ...      ...
546  13692  OUTSIDE INDONESIA          NaN   +07:00
547  13743               BALI  KARANG ASEM   +08:00
548  13788         JAWA TIMUR       JEMBER   +07:00
549  13876         JAWA TIMUR   BANYUWANGI   +07:00
550  13886         JAWA TIMUR       JEMBER   +07:00

[551 rows x 4 columns]

In [72]:
# Check basic information about the dataframe
print("Basic Information:")
farms.info()

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551 entries, 0 to 550
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        551 non-null    int64 
 1   province  479 non-null    object
 2   regency   458 non-null    object
 3   timezone  551 non-null    object
dtypes: int64(1), object(3)
memory usage: 17.3+ KB


In [73]:
# Check for missing values
print("\nMissing Values:")
farms.isnull().sum()


Missing Values:


id           0
province    72
regency     93
timezone     0
dtype: int64

In [74]:
# Select rows with NaN values in 'province' column
rows_with_nan_province = farms.loc[farms['province'].isna()]

# Print the rows
rows_with_nan_province[50:]

id province regency timezone
412  10689      NaN     NaN   +07:00
415  10805      NaN     NaN   +07:00
416  10806      NaN     NaN   +07:00
417  10808      NaN     NaN   +07:00
418  10809      NaN     NaN   +07:00
419  10811      NaN     NaN   +07:00
420  10813      NaN     NaN   +07:00
421  10830      NaN     NaN   +07:00
422  10841      NaN     NaN   +07:00
423  10842      NaN     NaN   +07:00
424  10845      NaN     NaN   +07:00
425  10849      NaN     NaN   +07:00
426  10855      NaN     NaN   +07:00
427  10857      NaN     NaN   +07:00
430  10882      NaN     NaN   +07:00
441  11069      NaN     NaN   +07:00
442  11070      NaN     NaN   +07:00
449  11203      NaN     NaN   +07:00
452  11258      NaN     NaN   +07:00
456  11381      NaN     NaN   +07:00
461  11465      NaN     NaN   +07:00
462  11466      NaN     NaN   +07:00

In [75]:
# Select rows with NaN values in 'regency' column
rows_with_nan_regency = farms.loc[farms['regency'].isna()]

# Print the rows
rows_with_nan_regency

id           province regency timezone
32    2960               ACEH     NaN   +07:00
43    3994            LAMPUNG     NaN   +07:00
44    3995            LAMPUNG     NaN   +07:00
166   7766  OUTSIDE INDONESIA     NaN   +07:00
235   8350                NaN     NaN   +07:00
..     ...                ...     ...      ...
478  11679  OUTSIDE INDONESIA     NaN   +07:00
496  13198  OUTSIDE INDONESIA     NaN   +05:00
497  13224  OUTSIDE INDONESIA     NaN   +05:00
499  13251  OUTSIDE INDONESIA     NaN   +07:00
546  13692  OUTSIDE INDONESIA     NaN   +07:00

[93 rows x 4 columns]

In [76]:
# Check unique values for object columns
object_columns = farms.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(farms[column].unique())


Unique values for province:
['JAWA BARAT' 'SULAWESI SELATAN' 'JAWA TIMUR' 'JAWA TENGAH' 'LAMPUNG'
 'BALI' 'GORONTALO' 'ACEH' 'BANTEN' 'RIAU' 'DI YOGYAKARTA'
 'KEPULAUAN BANGKA BELITUNG' 'SUMATERA BARAT' 'OUTSIDE INDONESIA'
 'SUMATERA SELATAN' nan 'NUSA TENGGARA BARAT' 'SULAWESI TENGAH'
 'SUMATERA UTARA' 'SULAWESI UTARA' 'SULAWESI BARAT']

Unique values for regency:
['SUBANG' 'BARRU' 'PACITAN' 'SITUBONDO' 'BANYUWANGI' 'DEMAK'
 'PESISIR BARAT' 'JEPARA' 'TULANGBAWANG' 'BULELENG' 'CILACAP' 'KENDAL'
 'PESAWARAN' 'POHUWATO' 'LAMPUNG SELATAN' nan 'PANDEGLANG' 'PURWOREJO'
 'INDRAMAYU' 'BENGKALIS' 'PROBOLINGGO' 'BANTUL' 'GARUT' 'SAMPANG'
 'BULUKUMBA' 'GRESIK' 'SERANG' 'BANGKA SELATAN' 'PANGANDARAN' 'PASURUAN'
 'SUMENEP' 'PATI' 'PEMALANG' 'BREBES' 'PIDIE JAYA' 'LAMONGAN'
 'TASIKMALAYA' 'AGAM' 'ACEH TIMUR' 'OGAN KOMERING ILIR' 'NGANJUK'
 'CIREBON' 'KEBUMEN' 'JEMBRANA' 'JEMBER' 'KOTA CIREBON' 'SUMBAWA'
 'ACEH UTARA' 'BANGKA' 'PINRANG' 'BANGKALAN' 'DONGGALA' 'KOTA TASIKMALAYA'
 'TEGAL' 'LAMPUNG TI

In [77]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
farms.describe()


Descriptive Statistics:


id
count    551.000000
mean    8625.956443
std     2937.544875
min      652.000000
25%     6369.500000
50%     8531.000000
75%    10710.000000
max    13886.000000

In [78]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
farms.duplicated().sum()


Duplicate Rows:


0

In [79]:
# Numeric Value Validation
# Example: Check for negative values in the 'id' column
negative_ids = farms[farms['id'] < 0]
print("\nNegative IDs:")
print(negative_ids)


Negative IDs:
Empty DataFrame
Columns: [id, province, regency, timezone]
Index: []


Based on the data validation results:

1. **Basic Information:** The dataframe consists of 551 entries and 4 columns. The 'province' and 'regency' columns have missing values, with 72 and 93 null values respectively.

2. **Unique Values for 'province':** The 'province' column contains various provinces where the farms are located, with 'JAWA BARAT' being the most common. There is also a category 'OUTSIDE INDONESIA' indicating farms located outside Indonesia.

3. **Unique Values for 'regency':** The 'regency' column contains various regencies where the farms are located, with 'SUBANG' being the most common. There is also a category 'nan' indicating missing values in this column.

4. **Unique Values for 'timezone':** The 'timezone' column indicates the timezone of the farms, with several different timezone offsets ranging from +02:00 to +08:00.

5. **Duplicate Rows:** There are no duplicate rows in the dataframe.

**Conclusion:**
- The dataset contains information about farms, including their locations (province and regency) and timezone.
- There are missing values in the 'province' and 'regency' columns, which may need to be addressed before further analysis.
- The data seems relatively clean, with no duplicate rows detected.

Further actions may include imputing missing values, if possible, and conducting exploratory data analysis to gain more insights into the farm data.

## Fasting

In [80]:
# sanity check
fasting

logged_date  cycle_id  fasting
0     2022-10-17     15804      1.0
1     2022-11-27     15804      0.0
2     2022-11-28     15804      0.0
3     2022-11-29     15804      0.0
4     2022-12-01     15804      1.0
...          ...       ...      ...
6184  2023-03-09     15301      1.0
6185  2023-03-15     15301      1.0
6186  2023-03-23     15301      1.0
6187  2023-04-06     15301      1.0
6188  2023-04-14     15301      1.0

[6189 rows x 3 columns]

In [81]:
# Check basic information about the dataframe
print("Basic Information:")
print(fasting.info())

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6189 entries, 0 to 6188
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   logged_date  6189 non-null   object 
 1   cycle_id     6189 non-null   int64  
 2   fasting      6172 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 145.2+ KB
None


In [82]:
# Check for missing values
print("\nMissing Values:")
print(fasting.isnull().sum())


Missing Values:
logged_date     0
cycle_id        0
fasting        17
dtype: int64


In [83]:
# Check unique values for object columns
object_columns = fasting.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(fasting[column].unique())


Unique values for logged_date:
['2022-10-17' '2022-11-27' '2022-11-28' '2022-11-29' '2022-12-01'
 '2021-05-20' '2022-08-16' '2022-03-28' '2022-04-10' '2022-04-18'
 '2022-04-17' '2022-04-16' '2022-04-15' '2022-04-14' '2022-04-13'
 '2022-04-12' '2022-09-10' '2022-09-19' '2022-09-20' '2022-09-21'
 '2022-09-22' '2022-09-23' '2022-09-24' '2022-09-25' '2022-10-05'
 '2022-10-04' '2022-10-22' '2022-10-23' '2023-03-01' '2023-03-02'
 '2021-11-16' '2022-10-19' '2022-10-24' '2022-10-26' '2022-11-11'
 '2022-11-12' '2022-11-13' '2022-11-26' '2022-12-03' '2022-12-06'
 '2022-12-07' '2022-12-10' '2022-12-11' '2022-12-09' '2022-12-19'
 '2022-12-21' '2022-12-23' '2022-12-24' '2022-12-31' '2023-01-02'
 '2023-01-01' '2023-01-05' '2023-01-07' '2022-11-18' '2023-03-13'
 '2023-03-14' '2023-03-15' '2023-03-16' '2023-03-17' '2023-03-18'
 '2023-03-19' '2023-03-20' '2023-03-21' '2023-03-22' '2023-03-23'
 '2023-03-24' '2023-03-25' '2023-03-26' '2023-03-27' '2023-03-28'
 '2023-03-29' '2023-03-30' '2023-03-31' '202

In [84]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
print(fasting.describe())


Descriptive Statistics:
           cycle_id      fasting
count   6189.000000  6172.000000
mean   17675.134755     0.242547
std     2820.779258     0.428658
min     7616.000000     0.000000
25%    16091.000000     0.000000
50%    17832.000000     0.000000
75%    19318.000000     0.000000
max    23531.000000     1.000000


In [85]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(fasting.duplicated().sum())


Duplicate Rows:
67


In [86]:
# Range Validation for Integer and Float Columns
numeric_columns = fasting.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = fasting[column].min()
    max_value = fasting[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")


Range for cycle_id: 7616 to 23531

Range for fasting: 0.0 to 1.0


In [87]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = fasting[~fasting['cycle_id'].isin(cycles['id'])]
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)


Invalid 'cycle_id' values:
     logged_date  cycle_id  fasting
101   2022-08-16     15068      0.0
102   2022-08-17     15068      0.0
103   2022-08-18     15068      0.0
104   2022-08-19     15068      0.0
105   2022-08-20     15068      0.0
...          ...       ...      ...
4617  2022-10-18     19048      0.0
4618  2022-10-19     19048      0.0
4619  2022-10-22     19048      0.0
4620  2022-10-24     19048      0.0
4621  2022-10-26     19048      0.0

[199 rows x 3 columns]


In [88]:
# Columns with missing values
columns_with_missing = fasting.columns[fasting.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(fasting.loc[fasting[column].isnull()])
    print("\n")

Missing values in column 'fasting':
     logged_date  cycle_id  fasting
830   2022-09-04     15970      NaN
831   2022-09-13     15970      NaN
1560  2022-09-04     17880      NaN
1561  2022-09-13     17880      NaN
1962  2023-05-02     18238      NaN
3689  2022-12-10     15869      NaN
4692  2022-09-04     20978      NaN
4693  2022-09-13     20978      NaN
4746  2023-01-19     22445      NaN
4750  2023-02-06     22445      NaN
4817  2022-09-07     15505      NaN
4818  2022-09-04     15505      NaN
4819  2022-09-13     15505      NaN
5039  2022-09-22      9090      NaN
5435  2022-09-07     19688      NaN
5436  2022-09-04     19688      NaN
5437  2022-09-13     19688      NaN




Here are the key points from the data validation of the "fasting" table:

1. **Basic Information**:
   - The dataset contains 6189 entries with 3 columns: `logged_date`, `cycle_id`, and `fasting`.
   - The data types are: `logged_date` (object), `cycle_id` (int64), and `fasting` (float64).

2. **Missing Values**:
   - The `logged_date` and `cycle_id` columns have no missing values.
   - The `fasting` column has 17 missing values.

3. **Duplicate Rows**:
   - There are 67 duplicate rows in the dataset.

4. **Range for Integer and Float Columns**:
   - The `cycle_id` values range from 7616 to 23531.
   - The `fasting` values range from 0.0 to 1.0.

These points provide a clear summary of the data validation results for the "fasting" table, highlighting the presence of missing values, duplicate rows, and the ranges of key numerical columns.

# Fastings

In [89]:
# sanity check
fastings

logged_date  cycle_id  fasting
0      2022-03-26   15013.0      1.0
1      2022-03-27   15013.0      0.0
2      2022-03-28   15013.0      0.0
3      2022-04-10   15013.0      1.0
4      2021-10-23   11848.0      1.0
...           ...       ...      ...
32374  2024-01-02   28500.0      1.0
32375  2024-01-02   28500.0      0.0
32376  2023-08-07   24650.0      1.0
32377  2023-09-06   24650.0      1.0
32378  2023-08-06   24650.0      1.0

[32379 rows x 3 columns]

In [91]:
# Check basic information about the dataframe
print("Basic Information:")
fastings.info()  # Display basic info about the dataframe including data types and non-null counts

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32379 entries, 0 to 32378
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   logged_date  32379 non-null  object 
 1   cycle_id     32379 non-null  float64
 2   fasting      32339 non-null  float64
dtypes: float64(2), object(1)
memory usage: 759.0+ KB


In [92]:
# Check for missing values
print("\nMissing Values:")
print(fastings.isnull().sum())  # Sum of missing values in each column


Missing Values:
logged_date     0
cycle_id        0
fasting        40
dtype: int64


In [93]:
# Check unique values for object columns
object_columns = fastings.select_dtypes(include='object').columns  # Identify columns with object data type
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(fastings[column].unique())  # Display unique values for each object column


Unique values for logged_date:
['2022-03-26' '2022-03-27' '2022-03-28' ... '2022-02-03' '2021-11-23'
 '2021-11-20']


In [94]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
print(fastings.describe())  # Display descriptive statistics for numerical columns


Descriptive Statistics:
           cycle_id       fasting
count  32379.000000  32339.000000
mean   20198.647364      0.269025
std     4592.291087      0.443460
min     4036.000000      0.000000
25%    17307.000000      0.000000
50%    18919.000000      0.000000
75%    24321.000000      1.000000
max    29659.000000      1.000000


In [95]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(fastings.duplicated().sum())  # Count duplicate rows in the dataframe


Duplicate Rows:
185


In [96]:

# Range Validation for Integer and Float Columns
numeric_columns = fastings.select_dtypes(include=['int64', 'float64']).columns  # Identify numeric columns
for column in numeric_columns:
    min_value = fastings[column].min()  # Find minimum value in the column
    max_value = fastings[column].max()  # Find maximum value in the column
    print(f"\nRange for {column}: {min_value} to {max_value}")  # Print the range of values


Range for cycle_id: 4036.0 to 29659.0

Range for fasting: 0.0 to 1.0


In [97]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = fastings[~fastings['cycle_id'].isin(cycles['id'])]  # Find invalid foreign key references
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)  # Print rows with invalid foreign key references


Invalid 'cycle_id' values:
Empty DataFrame
Columns: [logged_date, cycle_id, fasting]
Index: []


In [98]:
# Columns with missing values
columns_with_missing = fastings.columns[fastings.isnull().any()]  # Identify columns with missing values

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(fastings.loc[fastings[column].isnull()])  # Print rows with missing values for each column
    print("\n")

Missing values in column 'fasting':
      logged_date  cycle_id  fasting
1990   2023-09-16   23123.0      NaN
3128   2023-08-13   24814.0      NaN
3319   2022-12-10   19253.0      NaN
4524   2023-08-11   24692.0      NaN
4525   2023-08-11   24692.0      NaN
5583   2022-10-05   18036.0      NaN
5584   2022-10-04   18036.0      NaN
5790   2023-09-26   25577.0      NaN
5799   2023-10-05   25577.0      NaN
7569   2023-07-19   24300.0      NaN
7574   2023-08-14   24300.0      NaN
9340   2022-09-04   17628.0      NaN
9341   2022-09-13   17628.0      NaN
9914   2022-08-20   17186.0      NaN
11403  2023-05-02   20614.0      NaN
11519  2023-04-19   21597.0      NaN
12310  2022-11-30   19061.0      NaN
15564  2022-09-04   17632.0      NaN
15565  2022-09-13   17632.0      NaN
15727  2022-09-09   17625.0      NaN
15992  2023-01-19   19247.0      NaN
15996  2023-02-06   19247.0      NaN
16629  2022-07-24   16065.0      NaN
16654  2022-08-21   16065.0      NaN
16777  2022-09-07   17631.0      NaN
16

Here are the key points from the data validation of the "fastings" table:

1. **Basic Information**:
   - The dataset contains 32,379 entries with 3 columns: `logged_date`, `cycle_id`, and `fasting`.
   - The data types are: `logged_date` (object), `cycle_id` (float64), and `fasting` (float64).

2. **Missing Values**:
   - The `logged_date` and `cycle_id` columns have no missing values.
   - The `fasting` column has 40 missing values.

3. **Duplicate Rows**:
   - There are 185 duplicate rows in the dataset.

4. **Range for Integer and Float Columns**:
   - The `cycle_id` values range from 4036.0 to 29659.0.
   - The `fasting` values range from 0.0 to 1.0.

These points provide a summary of the data validation results for the "fastings" table, highlighting the presence of missing values, duplicate rows, and the ranges of key numerical columns.

## Feed Tray

In [7]:
# sanity check
feed_tray

id            logged_at       feed_logged_at  cycle_id  \
0          498  2021-11-19 17:09:00  2021-11-20 04:09:00     12163   
1          499  2021-11-19 17:09:00  2021-11-20 04:09:00     12163   
2          500  2021-11-20 09:14:00  2021-11-20 08:14:00     12163   
3          501  2021-11-20 09:14:00  2021-11-20 08:14:00     12163   
4         1643  2021-12-13 02:00:00  2021-12-13 00:00:00     13112   
...        ...                  ...                  ...       ...   
186659  285946  2024-03-28 18:00:00  2024-03-29 00:00:00     27415   
186660  285947  2024-03-28 18:00:00  2024-03-29 03:30:00     27415   
186661  285948  2024-03-28 18:00:00  2024-03-29 03:30:00     27415   
186662  285949  2024-03-28 18:00:00  2024-03-29 05:30:00     27415   
186663  285950  2024-03-28 18:00:00  2024-03-29 05:30:00     27415   

        tray_number  feed_remaining_percent  \
0                 1                       0   
1                 2                       0   
2                 1                       0   
3                 2                       0   
4                 2                       0   
...             ...                     ...   
186659            2                      33   
186660            1                      33   
186661            2                      33   
186662            1                      33   
186663            2                      33   

                                        remark           created_at  \
0                                          NaN  2021-11-20 04:12:03   
1                                          NaN  2021-11-20 04:12:03   
2                                          NaN  2021-11-20 08:15:17   
3                                          NaN  2021-11-20 08:15:17   
4       Anco 1 habis 30 menit, anco 2 55 menit  2021-12-14 01:18:59   
...                                        ...                  ...   
186659                                     NaN  2024-04-03 10:34:19   
186660                                     NaN  2024-04-03 10:34:19   
186661                                     NaN  2024-04-03 10:34:19   
186662                                     NaN  2024-04-03 10:34:19   
186663                                     NaN  2024-04-03 10:34:19   

                 updated_at local_feed_logged_at  
0       2021-11-20 04:12:03  2021-11-20 00:09:00  
1       2021-11-20 04:12:03  2021-11-20 00:09:00  
2       2021-11-20 08:15:17  2021-11-20 16:14:00  
3       2021-11-20 08:15:17  2021-11-20 16:14:00  
4       2021-12-16 00:12:44  2021-12-13 09:00:00  
...                     ...                  ...  
186659  2024-04-03 10:34:19  2024-03-29 01:00:00  
186660  2024-04-03 10:34:19  2024-03-29 01:00:00  
186661  2024-04-03 10:34:19  2024-03-29 01:00:00  
186662  2024-04-03 10:34:19  2024-03-29 01:00:00  
186663  2024-04-03 10:34:19  2024-03-29 01:00:00  

[186664 rows x 10 columns]

In [99]:
# Check basic information about the dataframe
print("Basic Information:")
print(feed_tray.info())  # Display basic info about the dataframe including data types and non-null counts

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186664 entries, 0 to 186663
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype 
---  ------                  --------------   ----- 
 0   id                      186664 non-null  int64 
 1   logged_at               186664 non-null  object
 2   feed_logged_at          186664 non-null  object
 3   cycle_id                186664 non-null  int64 
 4   tray_number             186664 non-null  int64 
 5   feed_remaining_percent  186664 non-null  int64 
 6   remark                  46381 non-null   object
 7   created_at              186664 non-null  object
 8   updated_at              186664 non-null  object
 9   local_feed_logged_at    186664 non-null  object
dtypes: int64(4), object(6)
memory usage: 14.2+ MB
None


In [100]:
# Check for missing values
print("\nMissing Values:")
print(feed_tray.isnull().sum())  # Sum of missing values in each column


Missing Values:
id                             0
logged_at                      0
feed_logged_at                 0
cycle_id                       0
tray_number                    0
feed_remaining_percent         0
remark                    140283
created_at                     0
updated_at                     0
local_feed_logged_at           0
dtype: int64


In [101]:
# Check unique values for object columns
object_columns = feed_tray.select_dtypes(include='object').columns  # Identify columns with object data type
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(feed_tray[column].unique())  # Display unique values for each object column


Unique values for logged_at:
['2021-11-19 17:09:00' '2021-11-20 09:14:00' '2021-12-13 02:00:00' ...
 '2024-03-27 18:00:00' '2024-03-28 18:00:00' '2024-03-23 18:00:00']

Unique values for feed_logged_at:
['2021-11-20 04:09:00' '2021-11-20 08:14:00' '2021-12-13 00:00:00' ...
 '2024-03-29 05:30:00' '2024-03-24 03:30:00' '2024-03-24 05:30:00']

Unique values for remark:
[nan 'Anco 1 habis 30 menit, anco 2 55 menit'
 'Anco 1 dan 2, 1jam 16 menit habis'
 'Anco 1 habis 1 jam\nAnco 2 habis 1 jam 15 menit' 'Udang sehat,,'
 'Anco 1 45 menit\nAnco 2 1 jam 10 menit' '1,5jam habis' '1 jam habis'
 'Anco 1, 1 jam\nAnco 2, 1 jam 45 menit'
 'Anco 1 : 1 jam 18 menit\nAnco 2 : 1 jam 40 menit'
 'Perkembangan udang normal sehat,, tingkat agresif tinggi'
 'Mepet 2 jam habisnya' '1 jam' '1 jam 50 menit'
 'Anco 1 habis 1 jam 50 menit' 'Keadaan udang moulting'
 'Dalam waktu 1jam kurang pakan di anco habiss,,, anco menggunakan 2%'
 '2 pakan habis dan 1 sisa sedikit pakan di anco'
 'pakan habis semua di 3 anco'

In [102]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
print(feed_tray.describe())  # Display descriptive statistics for numerical columns


Descriptive Statistics:
                  id       cycle_id    tray_number  feed_remaining_percent
count  186664.000000  186664.000000  186664.000000           186664.000000
mean   123263.899429   20091.738193       1.950221               10.079935
std     67748.121524    4137.425172       1.077650               19.511848
min       498.000000   12163.000000       1.000000                0.000000
25%     63660.750000   16162.000000       1.000000                0.000000
50%    122951.500000   19253.000000       2.000000                0.000000
75%    180322.250000   23739.000000       3.000000                0.000000
max    285950.000000   29874.000000       6.000000               66.000000


In [103]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(feed_tray.duplicated().sum())  # Count duplicate rows in the dataframe


Duplicate Rows:
0


In [104]:
# Range Validation for Integer and Float Columns
numeric_columns = feed_tray.select_dtypes(include=['int64', 'float64']).columns  # Identify numeric columns
for column in numeric_columns:
    min_value = feed_tray[column].min()  # Find minimum value in the column
    max_value = feed_tray[column].max()  # Find maximum value in the column
    print(f"\nRange for {column}: {min_value} to {max_value}")  # Print the range of values


Range for id: 498 to 285950

Range for cycle_id: 12163 to 29874

Range for tray_number: 1 to 6

Range for feed_remaining_percent: 0 to 66


In [105]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = feed_tray[~feed_tray['cycle_id'].isin(cycles['id'])]  # Find invalid foreign key references
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)  # Print rows with invalid foreign key references


Invalid 'cycle_id' values:
Empty DataFrame
Columns: [id, logged_at, feed_logged_at, cycle_id, tray_number, feed_remaining_percent, remark, created_at, updated_at, local_feed_logged_at]
Index: []


In [106]:

# Columns with missing values
columns_with_missing = feed_tray.columns[feed_tray.isnull().any()]  # Identify columns with missing values

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(feed_tray.loc[feed_tray[column].isnull()])  # Print rows with missing values for each column
    print("\n")

Missing values in column 'remark':
            id            logged_at       feed_logged_at  cycle_id  \
0          498  2021-11-19 17:09:00  2021-11-20 04:09:00     12163   
1          499  2021-11-19 17:09:00  2021-11-20 04:09:00     12163   
2          500  2021-11-20 09:14:00  2021-11-20 08:14:00     12163   
3          501  2021-11-20 09:14:00  2021-11-20 08:14:00     12163   
6         1765  2021-12-13 06:00:00  2021-12-13 04:00:00     13112   
...        ...                  ...                  ...       ...   
186659  285946  2024-03-28 18:00:00  2024-03-29 00:00:00     27415   
186660  285947  2024-03-28 18:00:00  2024-03-29 03:30:00     27415   
186661  285948  2024-03-28 18:00:00  2024-03-29 03:30:00     27415   
186662  285949  2024-03-28 18:00:00  2024-03-29 05:30:00     27415   
186663  285950  2024-03-28 18:00:00  2024-03-29 05:30:00     27415   

        tray_number  feed_remaining_percent remark           created_at  \
0                 1                       0    Na

Here are the key points from the data validation of the "feed_tray" table:

1. **Basic Information**:
   - The dataset contains 186,664 entries with 10 columns.
   - Columns and data types: `id` (int64), `logged_at` (object), `feed_logged_at` (object), `cycle_id` (int64), `tray_number` (int64), `feed_remaining_percent` (int64), `remark` (object), `created_at` (object), `updated_at` (object), `local_feed_logged_at` (object).

2. **Missing Values**:
   - The `remark` column has 140,283 missing values.
   - All other columns have no missing values.

3. **Descriptive Statistics**:
   - `id`: Ranges from 498 to 285950.
   - `cycle_id`: Ranges from 12163 to 29874.
   - `tray_number`: Ranges from 1 to 6.
   - `feed_remaining_percent`: Ranges from 0 to 66.
   - The mean value of `feed_remaining_percent` is approximately 10.08, with a standard deviation of 19.51.

4. **Duplicate Rows**:
   - There are no duplicate rows in the dataset.

These points provide a summary of the data validation results for the "feed_tray" table, highlighting the presence of missing values in the `remark` column, the absence of duplicate rows, and the ranges of key numerical columns.

## Feeds

In [8]:
# sanity check
feeds

cycle_id                logged_at  quantity
0          15013  2022-03-29 00:00:00.000       0.5
1          15013  2022-03-29 05:30:00.000       0.5
2          15013  2022-03-29 11:30:00.000       0.5
3          15013  2022-03-29 14:30:00.000       0.5
4          15013  2022-03-30 00:00:00.000       0.5
...          ...                      ...       ...
706903     24650  2023-09-15 21:47:00.000      10.0
706904     24650  2023-09-19 00:00:00.000      13.2
706905     24650  2023-09-20 00:00:00.000      14.0
706906     24650  2023-09-21 13:54:00.000      10.0
706907     24650  2023-09-22 00:47:00.000      14.0

[706908 rows x 3 columns]

In [107]:
# Check basic information about the dataframe
print("Basic Information:")
print(feeds.info())

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706908 entries, 0 to 706907
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   cycle_id   706908 non-null  int64  
 1   logged_at  706887 non-null  object 
 2   quantity   706887 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 16.2+ MB
None


In [108]:
# Check for missing values
print("\nMissing Values:")
print(feeds.isnull().sum())


Missing Values:
cycle_id      0
logged_at    21
quantity     21
dtype: int64


In [109]:
# Check unique values for object columns
object_columns = feeds.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(feeds[column].unique())


Unique values for logged_at:
['2022-03-29 00:00:00.000' '2022-03-29 05:30:00.000'
 '2022-03-29 11:30:00.000' ... '2023-09-15 21:47:00.000'
 '2023-09-21 13:54:00.000' '2023-09-22 00:47:00.000']


In [110]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
print(feeds.describe())


Descriptive Statistics:
            cycle_id       quantity
count  706908.000000  706887.000000
mean    21890.928919      17.064466
std      5434.180295      22.536168
min      3458.000000      -1.000000
25%     18395.000000       4.000000
50%     23633.000000      10.000000
75%     27089.000000      22.000000
max     29874.000000    2011.000000


In [111]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(feeds.duplicated().sum())


Duplicate Rows:
154995


In [112]:
# Range Validation for Integer and Float Columns
numeric_columns = feeds.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = feeds[column].min()
    max_value = feeds[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")


Range for cycle_id: 3458 to 29874

Range for quantity: -1.0 to 2011.0


In [113]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = feeds[~feeds['cycle_id'].isin(cycles['id'])]
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)


Invalid 'cycle_id' values:
Empty DataFrame
Columns: [cycle_id, logged_at, quantity]
Index: []


In [114]:
# Columns with missing values
columns_with_missing = feeds.columns[feeds.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(feeds.loc[feeds[column].isnull()])
    print("\n")

Missing values in column 'logged_at':
        cycle_id logged_at  quantity
54649      12850       NaN       NaN
95508      12072       NaN       NaN
147224     12854       NaN       NaN
148536     12855       NaN       NaN
150741     13452       NaN       NaN
150742     13452       NaN       NaN
238231     13112       NaN       NaN
249569     12341       NaN       NaN
249570     12341       NaN       NaN
258507     12065       NaN       NaN
291843     12857       NaN       NaN
343032     13451       NaN       NaN
395078     13308       NaN       NaN
395079     13308       NaN       NaN
446596     12067       NaN       NaN
501296     12853       NaN       NaN
505277     12851       NaN       NaN
520854     13114       NaN       NaN
610430     12852       NaN       NaN
703914     13166       NaN       NaN
703915     13166       NaN       NaN


Missing values in column 'quantity':
        cycle_id logged_at  quantity
54649      12850       NaN       NaN
95508      12072       NaN       Na

Here are the key points from the data validation of the "feeds" table:

1. **Basic Information**:
   - The dataset contains 706,908 entries with 3 columns.
   - Columns and data types: `cycle_id` (int64), `logged_at` (object), `quantity` (float64).

2. **Missing Values**:
   - `logged_at` column has 21 missing values.
   - `quantity` column has 21 missing values.
   - `cycle_id` column has no missing values.

3. **Descriptive Statistics**:
   - `cycle_id`: Ranges from 3458 to 29874.
   - `quantity`: Ranges from -1.0 to 2011.0.
   - The mean value of `quantity` is approximately 17.06, with a standard deviation of 22.54.
   - Notably, there are negative values in the `quantity` column, which may need further investigation.

4. **Duplicate Rows**:
   - There are 154,995 duplicate rows in the dataset.

These points summarize the data validation results for the "feeds" table, highlighting the presence of missing values in the `logged_at` and `quantity` columns, the existence of negative values in the `quantity` column, and a significant number of duplicate rows.

## Harvests

In [9]:
# sanity check
harvests

cycle_id           updated_at    size           created_at  weight  \
0      15013.0  2022-07-18 08:42:59  399.86  2022-07-18 08:42:59    0.01   
1      11848.0  2021-10-25 23:29:53  300.00  2021-10-24 08:38:53   46.00   
2      11848.0  2021-10-25 23:29:35  300.00  2021-10-25 23:29:35   10.00   
3       4666.0  2020-10-08 02:07:18  110.00  2020-10-08 02:07:18  270.50   
4       4666.0  2020-10-08 02:07:37  190.00  2020-10-08 02:07:37  270.50   
...        ...                  ...     ...                  ...     ...   
8082   28500.0  2024-03-17 06:34:46   90.00  2024-03-14 05:43:03   12.00   
8083   28500.0  2024-03-17 06:31:41  150.00  2024-03-14 05:47:06    4.00   
8084   11741.0  2022-10-06 05:23:38   80.00  2021-11-22 05:44:13  183.00   
8085   11741.0  2022-10-06 05:23:39   80.00  2021-11-22 05:55:49   30.00   
8086   24650.0  2023-09-25 10:40:25  200.00  2023-09-25 10:40:25  252.50   

           id harvested_at   status  selling_price  
0     11960.0   2022-04-17   Failed            NaN  
1      7520.0   2021-10-22     Full      1610000.0  
2      7546.0   2021-10-21  Partial       350000.0  
3      3009.0   2020-08-31   Failed            NaN  
4      3010.0   2020-08-31   Failed            NaN  
...       ...          ...      ...            ...  
8082  27731.0   2024-03-05     Full       720000.0  
8083  27732.0   2024-02-02  Partial       280000.0  
8084   8252.0   2021-11-20     Full     10431000.0  
8085   8254.0   2021-11-20  Partial      1200000.0  
8086  21615.0   2023-09-22     Full     10100000.0  

[8087 rows x 9 columns]

In [115]:
# Check basic information about the dataframe
print("Basic Information:")
print(harvests.info())

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8087 entries, 0 to 8086
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   cycle_id       8087 non-null   float64
 1   updated_at     8087 non-null   object 
 2   size           8087 non-null   float64
 3   created_at     8087 non-null   object 
 4   weight         8087 non-null   float64
 5   id             8087 non-null   float64
 6   harvested_at   8087 non-null   object 
 7   status         7824 non-null   object 
 8   selling_price  6294 non-null   float64
dtypes: float64(5), object(4)
memory usage: 568.7+ KB
None


In [116]:
# Check for missing values
print("\nMissing Values:")
print(harvests.isnull().sum())


Missing Values:
cycle_id            0
updated_at          0
size                0
created_at          0
weight              0
id                  0
harvested_at        0
status            263
selling_price    1793
dtype: int64


In [117]:
# Check unique values for object columns
object_columns = harvests.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(harvests[column].unique())


Unique values for updated_at:
['2022-07-18 08:42:59' '2021-10-25 23:29:53' '2021-10-25 23:29:35' ...
 '2024-03-17 06:34:46' '2022-10-06 05:23:39' '2023-09-25 10:40:25']

Unique values for created_at:
['2022-07-18 08:42:59' '2021-10-24 08:38:53' '2021-10-25 23:29:35' ...
 '2021-11-22 05:44:13' '2021-11-22 05:55:49' '2023-09-25 10:40:25']

Unique values for harvested_at:
['2022-04-17' '2021-10-22' '2021-10-21' ... '2023-04-10' '2022-01-16'
 '2023-12-31']

Unique values for status:
['Failed' 'Full' 'Partial' nan 'FINISIHING' 'Transfer ke N1 dan N2'
 'Transfer ke 10' 'Transfer ke 9' 'Transfer ke 8' 'finishing (pengesatan)'
 'Parsial' 'Patial' 'Transfer' 'Transfer ke Tambak']


In [118]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
print(harvests.describe())


Descriptive Statistics:
           cycle_id          size         weight            id  selling_price
count   8087.000000   8087.000000    8087.000000   8087.000000   6.294000e+03
mean   19871.768023    113.803389     774.636121  17307.678744   3.181221e+07
std     5785.357384    381.149658    4266.747605   6714.157986   1.646234e+08
min     3458.000000     10.000000       0.000000   2052.000000   0.000000e+00
25%    16342.500000     60.000000      47.970000  12549.500000   2.989368e+05
50%    19672.000000     86.000000     250.000000  16555.000000   6.247500e+06
75%    24742.500000    125.000000     667.695000  23111.500000   2.589123e+07
max    29874.000000  20000.000000  250000.000000  28468.000000   1.125000e+10


In [119]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(harvests.duplicated().sum())


Duplicate Rows:
0


In [120]:
# Range Validation for Integer and Float Columns
numeric_columns = harvests.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = harvests[column].min()
    max_value = harvests[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")


Range for cycle_id: 3458.0 to 29874.0

Range for size: 10.0 to 20000.0

Range for weight: 0.0 to 250000.0

Range for id: 2052.0 to 28468.0

Range for selling_price: 0.0 to 11250000000.0


In [121]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = harvests[~harvests['cycle_id'].isin(cycles['id'])]
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)


Invalid 'cycle_id' values:
Empty DataFrame
Columns: [cycle_id, updated_at, size, created_at, weight, id, harvested_at, status, selling_price]
Index: []


In [122]:
# Columns with missing values
columns_with_missing = harvests.columns[harvests.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(harvests.loc[harvests[column].isnull()])
    print("\n")

Missing values in column 'status':
      cycle_id           updated_at   size           created_at  weight  \
10     27095.0  2024-02-19 02:10:48  150.0  2024-02-19 02:10:48  119.00   
11     27095.0  2024-02-19 02:10:48   41.5  2024-02-19 02:10:48  169.00   
222    24191.0  2023-08-24 12:00:45  303.0  2023-08-24 12:00:45  147.00   
224    24191.0  2023-11-20 19:23:11  175.0  2023-11-20 19:23:11  217.00   
266    22173.0  2023-07-30 14:34:40  130.0  2023-07-30 14:32:32  210.00   
...        ...                  ...    ...                  ...     ...   
7961   19614.0  2023-07-12 04:25:46   54.0  2023-07-12 03:59:00  491.10   
7962   19614.0  2023-07-14 10:47:55   52.0  2023-07-14 10:47:55  534.14   
7963   19614.0  2023-07-14 10:47:55   51.0  2023-07-14 10:47:55  469.60   
7964   19614.0  2023-07-15 08:28:01   49.0  2023-07-15 08:28:01  528.12   
7965   19614.0  2023-07-15 08:28:01  100.0  2023-07-15 08:28:01   50.00   

           id harvested_at status  selling_price  
10    27046.0

Here are the key points from the data validation of the "harvests" table:

1. **Basic Information**:
   - The dataset contains 8,087 entries with 9 columns.
   - Columns and data types: 
     - `cycle_id` (float64)
     - `updated_at` (object)
     - `size` (float64)
     - `created_at` (object)
     - `weight` (float64)
     - `id` (float64)
     - `harvested_at` (object)
     - `status` (object)
     - `selling_price` (float64)

2. **Missing Values**:
   - `status` column has 263 missing values.
   - `selling_price` column has 1,793 missing values.
   - No missing values in other columns.

3. **Unique Values for `status`**:
   - The `status` column contains various unique values, including some with inconsistencies or typos such as 'FINISIHING', 'Parsial', 'Patial', etc.
   - Values include 'Failed', 'Full', 'Partial', 'finishing (pengesatan)', 'Transfer', and various forms of 'Transfer ke [location]'.

4. **Descriptive Statistics**:
   - `cycle_id`: Ranges from 3458.0 to 29874.0.
   - `size`: Ranges from 10.0 to 20000.0.
   - `weight`: Ranges from 0.0 to 250000.0.
   - `id`: Ranges from 2052.0 to 28468.0.
   - `selling_price`: Ranges from 0.0 to 11250000000.0.
   - The `weight` column has a mean of approximately 774.64 with a standard deviation of 4266.75, indicating high variability.
   - The `selling_price` column has a mean of approximately 31,812,210 and a standard deviation of 164,623,400, indicating extremely high variability and some very high values.

5. **Duplicate Rows**:
   - No duplicate rows in the dataset.

These points summarize the data validation results for the "harvests" table, highlighting missing values in the `status` and `selling_price` columns, inconsistencies in the `status` values, and the presence of outliers or potentially erroneous values in `weight` and `selling_price` columns.

## Measurements

In [10]:
# sanity check
measurements

pond_id  cycle_id measured_date  morning_temperature  \
0         31250     15009    2022-04-16               29.000   
1         21226     10897    2021-07-30                  NaN   
2         45694     27893    2023-12-07               29.342   
3         34732     17637    2022-08-11               24.900   
4             8     19874    2023-04-04               28.211   
...         ...       ...           ...                  ...   
139045    31457     19061    2022-12-22               27.000   
139046    31457     19061    2023-01-17               27.000   
139047       11      6126    2021-01-06                  NaN   
139048    44169     26483    2024-01-21               26.873   
139049    38747     23317    2023-07-28                  NaN   

        evening_temperature  morning_do  evening_do  morning_salinity  \
0                       NaN         NaN         NaN            28.000   
1                       NaN         NaN         NaN               NaN   
2                    32.445       4.355       6.253             2.155   
3                    25.900       5.100       3.800            21.000   
4                    30.869       3.106       4.370            12.673   
...                     ...         ...         ...               ...   
139045               30.000         NaN         NaN            24.000   
139046               29.000         NaN         NaN            23.000   
139047                  NaN         NaN         NaN               NaN   
139048               29.046       4.947       4.940            32.236   
139049                  NaN         NaN         NaN               NaN   

        evening_salinity  morning_pH  ...  nitrate  nitrite  alkalinity  \
0                    NaN       8.100  ...      NaN      NaN         NaN   
1                    NaN         NaN  ...      NaN      NaN         NaN   
2                  2.686       8.294  ...      NaN      NaN         NaN   
3                    NaN       7.400  ...      NaN    0.200         NaN   
4                 12.041       7.911  ...      NaN      NaN         NaN   
...                  ...         ...  ...      ...      ...         ...   
139045               NaN       7.600  ...      NaN      NaN         NaN   
139046               NaN       7.600  ...      NaN    1.892       100.0   
139047               NaN         NaN  ...      NaN      NaN         NaN   
139048            30.958       7.676  ...      NaN      NaN         NaN   
139049               NaN       7.800  ...      NaN      NaN         NaN   

        hardness  calcium  magnesium  carbonate  bicarbonate    tom  \
0            NaN      NaN        NaN        NaN          NaN    NaN   
1            NaN      NaN        NaN        NaN          NaN    NaN   
2            NaN      NaN        NaN        NaN          NaN    NaN   
3            NaN      NaN        NaN        NaN          NaN    NaN   
4            NaN      NaN        NaN        NaN          NaN    NaN   
...          ...      ...        ...        ...          ...    ...   
139045       NaN      NaN        NaN        NaN          NaN    NaN   
139046    4500.0    400.0      996.0        0.0        100.0  107.0   
139047       NaN      NaN        NaN        NaN          NaN    NaN   
139048       NaN      NaN        NaN        NaN          NaN    NaN   
139049       NaN      NaN        NaN        NaN          NaN    NaN   

        total_plankton_  
0                   NaN  
1                   NaN  
2                   NaN  
3                   NaN  
4                   NaN  
...                 ...  
139045              NaN  
139046         822500.0  
139047              NaN  
139048              NaN  
139049              NaN  

[139050 rows x 24 columns]

In [123]:
# Check basic information about the dataframe
print("Basic Information:")
print(measurements.info())

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139050 entries, 0 to 139049
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   pond_id              139050 non-null  int64  
 1   cycle_id             139050 non-null  int64  
 2   measured_date        139050 non-null  object 
 3   morning_temperature  97195 non-null   float64
 4   evening_temperature  89211 non-null   float64
 5   morning_do           77726 non-null   float64
 6   evening_do           73952 non-null   float64
 7   morning_salinity     92662 non-null   float64
 8   evening_salinity     65093 non-null   float64
 9   morning_pH           118935 non-null  float64
 10  evening_pH           60949 non-null   float64
 11  transparency         77300 non-null   float64
 12  turbidity            166 non-null     float64
 13  ammonia              3748 non-null    float64
 14  nitrate              2162 non-null    float64
 15

In [124]:
# Check for missing values
print("\nMissing Values:")
print(measurements.isnull().sum())


Missing Values:
pond_id                     0
cycle_id                    0
measured_date               0
morning_temperature     41855
evening_temperature     49839
morning_do              61324
evening_do              65098
morning_salinity        46388
evening_salinity        73957
morning_pH              20115
evening_pH              78101
transparency            61750
turbidity              138884
ammonia                135302
nitrate                136888
nitrite                129293
alkalinity             125533
hardness               133525
calcium                132458
magnesium              132430
carbonate              133762
bicarbonate            132372
tom                    131774
total_plankton_        126429
dtype: int64


In [125]:
# Check unique values for object columns
object_columns = measurements.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(measurements[column].unique())


Unique values for measured_date:
['2022-04-16' '2021-07-30' '2023-12-07' ... '2020-11-18' '2020-08-29'
 '2020-11-07']


In [126]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
print(measurements.describe())


Descriptive Statistics:
             pond_id      cycle_id  morning_temperature  evening_temperature  \
count  139050.000000  139050.00000         97195.000000         89211.000000   
mean    32589.530004   20268.85329            28.580945            29.908567   
std     10228.906407    5401.43651           106.896789             5.817013   
min         1.000000    3458.00000             0.000000             0.000000   
25%     30606.000000   16776.00000            27.000000            28.900000   
50%     34706.000000   20197.00000            28.000000            30.000000   
75%     39152.000000   24739.00000            29.000000            31.000000   
max     47282.000000   29874.00000         27341.000000          1078.933333   

         morning_do    evening_do  morning_salinity  evening_salinity  \
count  77726.000000  73952.000000      92662.000000      65093.000000   
mean       5.904100      6.005278         22.777202         22.090321   
std      216.810423     30.444501  

In [127]:

# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(measurements.duplicated().sum())



Duplicate Rows:
0


In [128]:
# Range Validation for Integer and Float Columns
numeric_columns = measurements.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = measurements[column].min()
    max_value = measurements[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")



Range for pond_id: 1 to 47282

Range for cycle_id: 3458 to 29874

Range for morning_temperature: 0.0 to 27341.0

Range for evening_temperature: 0.0 to 1078.933333333

Range for morning_do: -52.885 to 60043.0

Range for evening_do: -62.837 to 6706.0

Range for morning_salinity: -25.0 to 15734.0

Range for evening_salinity: 0.0 to 33958.0

Range for morning_pH: 0.0 to 7421.0

Range for evening_pH: 0.0 to 862.0

Range for transparency: -35.0 to 1110.0

Range for turbidity: 0.0 to 374144.855

Range for ammonia: 0.0 to 2057.0

Range for nitrate: 0.0 to 1272.0

Range for nitrite: 0.0 to 48031.0

Range for alkalinity: 0.0 to 19589.0

Range for hardness: 0.0 to 2000000.0

Range for calcium: 0.0 to 11250.0

Range for magnesium: 0.0 to 32000.0

Range for carbonate: 0.0 to 2400.0

Range for bicarbonate: 0.0 to 19589.0

Range for tom: -15.17 to 73312.0

Range for total_plankton_: 0.0 to 212505333.0


In [129]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = measurements[~measurements['cycle_id'].isin(cycles['id'])]
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)


Invalid 'cycle_id' values:
Empty DataFrame
Columns: [pond_id, cycle_id, measured_date, morning_temperature, evening_temperature, morning_do, evening_do, morning_salinity, evening_salinity, morning_pH, evening_pH, transparency, turbidity, ammonia, nitrate, nitrite, alkalinity, hardness, calcium, magnesium, carbonate, bicarbonate, tom, total_plankton_]
Index: []

[0 rows x 24 columns]


In [130]:
# Columns with missing values
columns_with_missing = measurements.columns[measurements.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(measurements.loc[measurements[column].isnull()])
    print("\n")

Missing values in column 'morning_temperature':
        pond_id  cycle_id measured_date  morning_temperature  \
1         21226     10897    2021-07-30                  NaN   
5         45886     27758    2023-12-13                  NaN   
11        15564      4751    2020-08-07                  NaN   
13        38738     23109    2023-09-01                  NaN   
14        38764     25081    2023-10-17                  NaN   
...         ...       ...           ...                  ...   
139028    37706     20189    2023-03-30                  NaN   
139042    38466     20765    2023-02-20                  NaN   
139044    24569     15980    2022-05-20                  NaN   
139047       11      6126    2021-01-06                  NaN   
139049    38747     23317    2023-07-28                  NaN   

        evening_temperature  morning_do  evening_do  morning_salinity  \
1                       NaN         NaN         NaN               NaN   
5                       NaN         N

Here are the key points from the data validation of the "measurements" table:

### Basic Information:
- **Total Entries**: 139,050
- **Total Columns**: 24
- **Data Types**:
  - **Integer (int64)**: `pond_id`, `cycle_id`
  - **Float (float64)**: 21 columns including `morning_temperature`, `evening_temperature`, `morning_do`, `evening_do`, `morning_salinity`, `evening_salinity`, etc.
  - **Object (string)**: `measured_date`

### Missing Values:
- Significant missing values across various columns:
  - `morning_temperature`: 41,855 missing
  - `evening_temperature`: 49,839 missing
  - `morning_do`: 61,324 missing
  - `evening_do`: 65,098 missing
  - `morning_salinity`: 46,388 missing
  - `evening_salinity`: 73,957 missing
  - `morning_pH`: 20,115 missing
  - `evening_pH`: 78,101 missing
  - `transparency`: 61,750 missing
  - `turbidity`: 138,884 missing (almost entirely missing)
  - `ammonia`: 135,302 missing
  - `nitrate`: 136,888 missing
  - `nitrite`: 129,293 missing
  - `alkalinity`: 125,533 missing
  - `hardness`: 133,525 missing
  - `calcium`: 132,458 missing
  - `magnesium`: 132,430 missing
  - `carbonate`: 133,762 missing
  - `bicarbonate`: 132,372 missing
  - `tom`: 131,774 missing
  - `total_plankton_`: 126,429 missing

### Descriptive Statistics:
- **pond_id**: 
  - Range: 1 to 47,282
- **cycle_id**: 
  - Range: 3,458 to 29,874
- **morning_temperature**: 
  - Range: 0.0 to 27,341.0
- **evening_temperature**: 
  - Range: 0.0 to 1,078.933
- **morning_do**: 
  - Range: -52.885 to 60,043.0
- **evening_do**: 
  - Range: -62.837 to 6,706.0
- **morning_salinity**: 
  - Range: -25.0 to 15,734.0
- **evening_salinity**: 
  - Range: 0.0 to 33,958.0
- **morning_pH**: 
  - Range: 0.0 to 7,421.0
- **evening_pH**: 
  - Range: 0.0 to 862.0
- **transparency**: 
  - Range: -35.0 to 1,110.0
- **turbidity**: 
  - Range: 0.0 to 374,144.855
- **ammonia**: 
  - Range: 0.0 to 2,057.0
- **nitrate**: 
  - Range: 0.0 to 1,272.0
- **nitrite**: 
  - Range: 0.0 to 48,031.0
- **alkalinity**: 
  - Range: 0.0 to 19,589.0
- **hardness**: 
  - Range: 0.0 to 2,000,000.0
- **calcium**: 
  - Range: 0.0 to 11,250.0
- **magnesium**: 
  - Range: 0.0 to 32,000.0
- **carbonate**: 
  - Range: 0.0 to 2,400.0
- **bicarbonate**: 
  - Range: 0.0 to 19,589.0
- **tom**: 
  - Range: -15.17 to 73,312.0
- **total_plankton_**: 
  - Range: 0.0 to 212,505,333.0

### Duplicate Rows:
- No duplicate rows in the dataset.

### Key Observations:
1. **High Variability**: Many columns show high variability and wide ranges, indicating the presence of outliers or erroneous values.
2. **Missing Data**: Numerous columns have substantial amounts of missing data, especially `turbidity`, `ammonia`, `nitrate`, `nitrite`, `alkalinity`, `hardness`, `calcium`, `magnesium`, `carbonate`, `bicarbonate`, `tom`, and `total_plankton_`.
3. **Negative and Unrealistic Values**: Some columns have negative or unrealistic values, e.g., `morning_do` and `evening_do` have negative values, `morning_temperature` and `evening_temperature` have extremely high values, which are likely errors.

These points summarize the data validation results for the "measurements" table, highlighting significant missing data, potential outliers, and unrealistic values. This suggests a need for further data cleaning and validation to ensure the dataset's quality and reliability.

# Mortalities

In [11]:
# sanity check
mortalities

id  cycle_id  quantity recorded_at           created_at  \
0        185      8007     83334  2021-03-04  2021-03-04 03:46:42   
1        186      8007     43334  2021-03-05  2021-03-05 06:47:30   
2        188      8139       870  2021-03-04  2021-03-11 09:00:34   
3        189      8139      1160  2021-03-05  2021-03-11 09:02:41   
4        190      8139      2030  2021-03-07  2021-03-11 09:03:27   
...      ...       ...       ...         ...                  ...   
13216  26188     27415      2565  2024-03-31  2024-04-03 06:39:15   
13217  26189     27415      2850  2024-04-01  2024-04-03 06:39:49   
13218  26190     27415      1425  2024-04-02  2024-04-03 06:40:05   
13219  26191     27416       898  2024-03-29  2024-04-03 06:40:39   
13220  26192     27416      1890  2024-03-30  2024-04-03 06:41:07   

                updated_at  average_weight  
0      2024-01-08 11:40:40            1.50  
1      2024-01-08 11:40:40            1.50  
2      2024-01-08 11:40:40            3.45  
3      2024-01-08 11:40:40            3.45  
4      2024-01-08 11:40:40            3.45  
...                    ...             ...  
13216  2024-04-03 06:39:15           17.54  
13217  2024-04-03 06:39:49           17.54  
13218  2024-04-03 06:40:05           17.54  
13219  2024-04-03 06:40:39           15.87  
13220  2024-04-03 06:41:07           15.87  

[13221 rows x 7 columns]

In [131]:
# Check basic information about the dataframe
print("Basic Information:")
print(mortalities.info())

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13221 entries, 0 to 13220
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              13221 non-null  int64  
 1   cycle_id        13221 non-null  int64  
 2   quantity        13221 non-null  int64  
 3   recorded_at     13221 non-null  object 
 4   created_at      13221 non-null  object 
 5   updated_at      13221 non-null  object 
 6   average_weight  13221 non-null  float64
dtypes: float64(1), int64(3), object(3)
memory usage: 723.1+ KB
None


In [132]:
# Check for missing values
print("\nMissing Values:")
print(mortalities.isnull().sum())


Missing Values:
id                0
cycle_id          0
quantity          0
recorded_at       0
created_at        0
updated_at        0
average_weight    0
dtype: int64


In [133]:
# Check unique values for object columns
object_columns = mortalities.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(mortalities[column].unique())


Unique values for recorded_at:
['2021-03-04' '2021-03-05' '2021-03-07' '2021-03-09' '2021-03-28'
 '2021-01-22' '2021-02-05' '2021-02-19' '2021-04-11' '2021-04-12'
 '2021-04-10' '2021-05-29' '2021-05-30' '2021-05-15' '2021-05-16'
 '2021-05-17' '2021-06-04' '2021-06-02' '2021-06-03' '2021-06-07'
 '2021-06-05' '2021-06-08' '2021-06-06' '2021-07-27' '2021-07-25'
 '2021-07-21' '2021-07-23' '2021-07-26' '2021-07-24' '2021-06-14'
 '2021-07-09' '2021-08-09' '2021-07-22' '2021-08-15' '2021-08-16'
 '2021-08-17' '2021-08-18' '2021-08-19' '2021-08-27' '2021-08-14'
 '2021-08-13' '2021-08-12' '2021-08-22' '2021-08-23' '2021-08-24'
 '2021-08-25' '2021-08-26' '2021-08-20' '2021-08-21' '2021-09-13'
 '2021-09-12' '2021-09-10' '2021-09-15' '2021-09-16' '2021-09-17'
 '2021-09-07' '2021-09-08' '2021-09-09' '2021-10-01' '2021-10-02'
 '2021-10-07' '2021-10-11' '2021-10-13' '2021-10-12' '2021-10-14'
 '2021-10-15' '2021-08-29' '2021-09-03' '2021-09-05' '2021-09-24'
 '2021-09-25' '2021-09-28' '2021-10-04' '202

In [134]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
print(mortalities.describe())


Descriptive Statistics:
                 id      cycle_id      quantity  average_weight
count  13221.000000  13221.000000  1.322100e+04    13221.000000
mean   14307.947810  20844.158763  1.834642e+03        9.613240
std     5630.215217   4098.897296  8.721018e+04       17.196472
min      185.000000   7273.000000  1.000000e+00        0.000000
25%     9763.000000  17726.000000  6.000000e+01        4.550000
50%    13998.000000  19676.000000  2.000000e+02        7.890000
75%    18858.000000  24092.000000  7.560000e+02       13.040000
max    26192.000000  29579.000000  1.000000e+07     1428.570000


In [135]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(mortalities.duplicated().sum())


Duplicate Rows:
0


In [136]:
# Range Validation for Integer and Float Columns
numeric_columns = mortalities.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = mortalities[column].min()
    max_value = mortalities[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")


Range for id: 185 to 26192

Range for cycle_id: 7273 to 29579

Range for quantity: 1 to 10000000

Range for average_weight: 0.0 to 1428.57


In [137]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = mortalities[~mortalities['cycle_id'].isin(cycles['id'])]
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)


Invalid 'cycle_id' values:
Empty DataFrame
Columns: [id, cycle_id, quantity, recorded_at, created_at, updated_at, average_weight]
Index: []


In [138]:
# Columns with missing values
columns_with_missing = mortalities.columns[mortalities.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(mortalities.loc[mortalities[column].isnull()])
    print("\n")

Here are the key points from the data validation of the "mortalities" table:

### Basic Information:
- **Total Entries**: 13,221
- **Total Columns**: 7
- **Data Types**:
  - **Integer (int64)**: `id`, `cycle_id`, `quantity`
  - **Float (float64)**: `average_weight`
  - **Object (string)**: `recorded_at`, `created_at`, `updated_at`

### Missing Values:
- There are no missing values in this dataset.

### Descriptive Statistics:
- **id**:
  - Count: 13,221
  - Mean: 14,307.95
  - Std: 5,630.22
  - Min: 185
  - 25%: 9,763
  - 50%: 13,998
  - 75%: 18,858
  - Max: 26,192

- **cycle_id**:
  - Count: 13,221
  - Mean: 20,844.16
  - Std: 4,098.90
  - Min: 7,273
  - 25%: 17,726
  - 50%: 19,676
  - 75%: 24,092
  - Max: 29,579

- **quantity**:
  - Count: 13,221
  - Mean: 1,834.64
  - Std: 87,210.18
  - Min: 1
  - 25%: 60
  - 50%: 200
  - 75%: 756
  - Max: 10,000,000

- **average_weight**:
  - Count: 13,221
  - Mean: 9.61
  - Std: 17.20
  - Min: 0.0
  - 25%: 4.55
  - 50%: 7.89
  - 75%: 13.04
  - Max: 1,428.57

### Duplicate Rows:
- There are no duplicate rows in the dataset.

### Key Observations:
1. **High Variability**: The `quantity` column shows extremely high variability with a standard deviation of 87,210.18, and the values range from 1 to 10,000,000. This indicates potential outliers or data entry errors.
2. **Realistic Values**: The `average_weight` column seems to have a realistic distribution, though there are some high values (e.g., max value of 1,428.57), which might need verification.
3. **No Missing Data**: This dataset has complete data with no missing values.

These points summarize the data validation results for the "mortalities" table, highlighting the need to verify high variability and potential outliers in the `quantity` column. The dataset overall appears clean with no missing values or duplicates.

## Ponds

In [12]:
# sanity check
ponds

id  farm_id  length  width  deep               created_at  \
0     2117        8     NaN    NaN   NaN  2018-04-19 20:09:43.000   
1        9        3   16.70  36.20   NaN  2018-03-07 19:05:09.000   
2     2116        8     NaN    NaN   NaN  2018-04-19 20:09:43.000   
3        7        3   46.50  32.60   1.1  2018-03-07 19:05:09.000   
4        8        3   48.50  33.00   1.1  2018-03-07 19:05:09.000   
..     ...      ...     ...    ...   ...                      ...   
333  44514    12530   31.00  30.00   1.3  2023-10-10 05:40:12.000   
334  37697     9987   81.65  61.24   NaN  2022-12-23 06:33:28.000   
335  44579    12542   21.00  14.00   1.3  2023-10-12 01:56:21.000   
336  44613    12553   40.00  40.00   1.5  2023-10-14 03:18:53.000   
337  44982    13228   53.00  45.00   1.0  2023-10-22 02:26:02.000   

                  updated_at               record_id             extracted_at  \
0    2018-04-19 20:09:43.000   ponds_2023_12_21_2117  2023-12-21 17:02:10.000   
1    2018-03-15 00:58:08.000       ponds_2024_4_12_9  2024-04-12 17:02:11.000   
2    2018-04-19 20:09:43.000   ponds_2023_12_21_2116  2023-12-21 17:02:10.000   
3    2018-03-15 00:51:55.000       ponds_2024_4_12_7  2024-04-12 17:02:11.000   
4    2022-05-28 13:31:07.000       ponds_2024_4_12_8  2024-04-12 17:02:11.000   
..                       ...                     ...                      ...   
333  2023-10-10 05:40:12.000  ponds_2023_10_11_44514  2023-10-11 17:02:18.000   
334  2022-12-23 06:33:28.000   ponds_2024_4_12_37697  2024-04-12 17:02:11.000   
335  2023-10-12 01:56:21.000   ponds_2024_4_12_44579  2024-04-12 17:02:11.000   
336  2023-10-14 03:23:49.000   ponds_2024_4_12_44613  2024-04-12 17:02:11.000   
337  2024-03-09 14:22:53.000   ponds_2024_4_12_44982  2024-04-12 17:02:11.000   

     max_seed_density  
0                 NaN  
1                 NaN  
2                 NaN  
3          131.926121  
4          124.921924  
..                ...  
333        129.032258  
334          0.012000  
335               NaN  
336        168.750000  
337         35.220126  

[338 rows x 10 columns]

In [32]:
# Check basic information about the dataframe
print("Basic Information:")
ponds.info()

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                338 non-null    int64  
 1   farm_id           338 non-null    int64  
 2   length            315 non-null    float64
 3   width             309 non-null    float64
 4   deep              246 non-null    float64
 5   created_at        338 non-null    object 
 6   updated_at        338 non-null    object 
 7   record_id         338 non-null    object 
 8   extracted_at      338 non-null    object 
 9   max_seed_density  135 non-null    float64
dtypes: float64(4), int64(2), object(4)
memory usage: 26.5+ KB


In [33]:
# Check for missing values
print("\nMissing Values:")
ponds.isnull().sum()


Missing Values:


id                    0
farm_id               0
length               23
width                29
deep                 92
created_at            0
updated_at            0
record_id             0
extracted_at          0
max_seed_density    203
dtype: int64

In [38]:
# Columns with missing values
columns_with_missing = ponds.columns[ponds.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(ponds.loc[ponds[column].isnull()])
    print("\n")

Missing values in column 'length':
        id  farm_id  length  width  deep               created_at  \
0     2117        8     NaN    NaN   NaN  2018-04-19 20:09:43.000   
2     2116        8     NaN    NaN   NaN  2018-04-19 20:09:43.000   
6     2118        8     NaN    NaN   NaN  2018-04-19 20:09:43.000   
8     2114        8     NaN    NaN   NaN  2018-04-19 20:09:43.000   
17   16883        3     NaN    NaN   1.7  2020-09-10 00:39:06.000   
20   28974     7388     NaN    NaN   NaN  2021-12-05 12:16:47.000   
21    2122       11     NaN    NaN   NaN  2018-04-19 21:06:38.000   
82   28972     7388     NaN    NaN   NaN  2021-12-05 12:16:47.000   
123   2123       11     NaN    NaN   NaN  2018-04-19 21:06:38.000   
124   2125       11     NaN    NaN   NaN  2018-04-19 21:06:38.000   
126   2140        2     NaN    NaN   NaN  2018-04-19 22:11:57.000   
174   2115        8     NaN    NaN   NaN  2018-04-19 20:09:43.000   
175   8360        2     NaN    NaN   NaN  2019-09-01 02:26:42.000   

In [34]:
# Check unique values for object columns
object_columns = ponds.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(ponds[column].unique())


Unique values for created_at:
['2018-04-19 20:09:43.000' '2018-03-07 19:05:09.000'
 '2021-10-04 03:49:38.000' '2021-11-30 08:59:31.000'
 '2020-10-12 07:28:28.000' '2021-09-14 00:54:35.000'
 '2021-11-28 14:35:15.000' '2020-09-10 00:39:06.000'
 '2021-12-05 12:16:47.000' '2018-04-19 21:06:38.000'
 '2023-10-11 04:32:31.000' '2023-10-12 05:49:59.000'
 '2023-10-15 14:13:00.000' '2023-10-15 17:14:49.000'
 '2023-10-16 07:20:16.000' '2023-10-21 02:22:21.000'
 '2023-10-25 01:21:43.000' '2018-04-19 22:11:57.000'
 '2023-10-09 17:17:42.000' '2023-10-15 17:14:48.000'
 '2023-10-16 02:03:22.000' '2023-10-20 09:18:14.000'
 '2023-10-21 04:22:40.000' '2023-10-24 13:15:38.000'
 '2023-10-26 03:26:52.000' '2021-11-28 19:40:16.000'
 '2021-11-28 21:36:36.000' '2021-10-04 11:45:09.000'
 '2021-11-28 14:35:14.000' '2021-11-30 11:49:50.000'
 '2021-11-28 17:03:39.000' '2023-10-18 02:33:17.000'
 '2021-11-28 16:39:53.000' '2024-01-10 00:16:47.000'
 '2022-10-26 04:13:02.000' '2023-09-01 13:33:59.000'
 '2023-10-12 01

In [35]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
ponds.describe()


Descriptive Statistics:


id       farm_id      length       width        deep  \
count    338.000000    338.000000  315.000000  309.000000  246.000000   
mean   36899.159763  10151.973373   46.604698   29.845825    7.133537   
std    12968.985879   4008.835331   37.879973   18.142403   26.681219   
min        1.000000      2.000000    0.600000    0.450000    0.900000   
25%    28825.250000   7365.000000   30.000000   20.000000    1.000000   
50%    44596.500000  12546.500000   36.510000   30.000000    1.300000   
75%    44702.750000  12562.000000   50.000000   40.000000    1.600000   
max    47762.000000  13378.000000  253.660000  190.240000  150.000000   

       max_seed_density  
count        135.000000  
mean         248.672850  
std         1077.046893  
min            0.000625  
25%           63.783784  
50%          120.000000  
75%          185.205992  
max        12500.000000

In [36]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
print(ponds.duplicated().sum())


Duplicate Rows:
0


In [37]:
# Range Validation for Integer and Float Columns
numeric_columns = ponds.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = ponds[column].min()
    max_value = ponds[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")


Range for id: 1 to 47762

Range for farm_id: 2 to 13378

Range for length: 0.6 to 253.66

Range for width: 0.45 to 190.24

Range for deep: 0.9 to 150.0

Range for max_seed_density: 0.000625 to 12500.0


Based on the data validation results, here are some key points and conclusions:

1. **Basic Information:**
    - The `ponds` DataFrame has 338 entries and 10 columns.
    - Data types include integers (2 columns), floats (4 columns), and objects (4 columns).

2. **Missing Values:**
    - The `length` column has 23 missing values.
    - The `width` column has 29 missing values.
    - The `deep` column has 92 missing values.
    - The `max_seed_density` column has 203 missing values.
    - Columns `id`, `farm_id`, `created_at`, `updated_at`, `record_id`, and `extracted_at` have no missing values.

3. **Descriptive Statistics:**
    - Columns `id` and `farm_id` show a wide range of values, indicating significant variation in the data.
    - Columns `length`, `width`, and `deep` show a broad range of values from minimum to maximum, suggesting variability in pond dimensions.
    - The `max_seed_density` column has a very wide range, with some extreme values (outliers).

4. **Duplicate Rows:**
    - There are no duplicate rows in the `ponds` DataFrame.

5. **Range for Columns:**
    - `id`: 1 to 47762
    - `farm_id`: 2 to 13378
    - `length`: 0.6 to 253.66
    - `width`: 0.45 to 190.24
    - `deep`: 0.9 to 150.0
    - `max_seed_density`: 0.000625 to 12500.0

### Additional Points:

- **Missing Values:** Columns `length`, `width`, `deep`, and `max_seed_density` have missing values that need to be addressed, either through imputation or data cleaning, depending on the analysis requirements.
  
- **Outliers:** The `max_seed_density` column shows a very wide range of values, indicating the presence of outliers. These outliers might need to be handled or further analyzed to understand their cause.

- **Date Columns:** The columns `created_at`, `updated_at`, and `extracted_at` are of type object and should be converted to datetime type for more accurate time-based analysis.

Overall, the data validation indicates that the `ponds` dataset has several challenges related to missing values and outliers, which need to be addressed for further analysis.

## Samplings

In [13]:
# sanity check
samplings

cycle_id           updated_at  sampled_at           created_at  \
0       18747.0  2022-10-07 03:26:30  2022-09-24  2022-10-07 02:10:49   
1       18747.0  2022-10-07 03:27:27  2022-10-01  2022-10-07 03:27:27   
2       18747.0  2022-10-08 01:30:56  2022-10-08  2022-10-08 01:30:56   
3       18747.0  2022-10-15 03:24:26  2022-10-15  2022-10-15 03:24:26   
4       27095.0  2023-11-05 09:03:39  2023-10-07  2023-11-05 09:03:39   
...         ...                  ...         ...                  ...   
15027   11741.0  2021-11-13 02:38:57  2021-11-10  2021-11-13 02:38:57   
15028   11741.0  2021-11-18 12:49:02  2021-11-17  2021-11-18 12:49:02   
15029   24650.0  2023-09-07 23:59:57  2023-09-08  2023-09-07 23:59:57   
15030   24650.0  2023-09-15 00:15:13  2023-09-15  2023-09-15 00:15:13   
15031   24650.0  2023-09-22 02:04:08  2023-09-22  2023-09-20 06:17:53   

       average_weight       id  \
0                4.91  32508.0   
1                7.12  32534.0   
2                9.75  32575.0   
3               11.15  32864.0   
4                4.79  52037.0   
...               ...      ...   
15027           11.14  20247.0   
15028           11.38  20579.0   
15029            3.41  47154.0   
15030            3.48  47603.0   
15031            4.33  47976.0   

                                                  remark  
0      Size 204\nP/H = 99 kg\nP/K = 2.020 kg\nSamplin...  
1      Size 140\nADG = 0,31\nP/H = 139 kg\nP/K = 2.88...  
2      Size 103\nADG = 0,38\nP/H = 160 kg\nP/K = 3.94...  
3      Size 90\nADG 0,23\nP/H = 180 kg\nP/K = 5.149 k...  
4                                                    NaN  
...                                                  ...  
15027                                                NaN  
15028                                                NaN  
15029                                           size 293  
15030                                           size 287  
15031                                           size 230  

[15032 rows x 7 columns]

In [50]:
# Check basic information about the dataframe
print("Basic Information:")
samplings.info()

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15032 entries, 0 to 15031
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   cycle_id        15032 non-null  float64
 1   updated_at      15032 non-null  object 
 2   sampled_at      15032 non-null  object 
 3   created_at      15032 non-null  object 
 4   average_weight  15032 non-null  float64
 5   id              15032 non-null  float64
 6   remark          1339 non-null   object 
dtypes: float64(3), object(4)
memory usage: 822.2+ KB


In [42]:

# Check for missing values
print("\nMissing Values:")
print(samplings.isnull().sum())



Missing Values:
cycle_id              0
updated_at            0
sampled_at            0
created_at            0
average_weight        0
id                    0
remark            13693
dtype: int64


In [40]:
# Columns with missing values
columns_with_missing = samplings.columns[samplings.isnull().any()]

# Iterate over columns with missing values
for column in columns_with_missing:
    print(f"Missing values in column '{column}':")
    print(samplings.loc[samplings[column].isnull()])
    print("\n")

Missing values in column 'remark':
       cycle_id           updated_at  sampled_at           created_at  \
4       27095.0  2023-11-05 09:03:39  2023-10-07  2023-11-05 09:03:39   
5       27095.0  2023-11-05 09:04:18  2023-10-14  2023-11-05 09:04:18   
6       27095.0  2023-11-05 09:04:55  2023-10-21  2023-11-05 09:04:55   
7       27095.0  2023-11-05 09:05:41  2023-10-28  2023-11-05 09:05:41   
8       27095.0  2023-11-05 09:06:23  2023-11-03  2023-11-05 09:06:23   
...         ...                  ...         ...                  ...   
15024   11741.0  2021-10-21 06:38:34  2021-10-20  2021-10-21 06:38:34   
15025   11741.0  2021-10-27 13:18:03  2021-10-27  2021-10-27 13:18:03   
15026   11741.0  2021-11-04 02:27:05  2021-11-03  2021-11-04 02:27:05   
15027   11741.0  2021-11-13 02:38:57  2021-11-10  2021-11-13 02:38:57   
15028   11741.0  2021-11-18 12:49:02  2021-11-17  2021-11-18 12:49:02   

       average_weight       id remark  
4                4.79  52037.0    NaN  
5       

In [43]:
# Check unique values for object columns
object_columns = samplings.select_dtypes(include='object').columns
for column in object_columns:
    print(f"\nUnique values for {column}:")
    print(samplings[column].unique())



Unique values for updated_at:
['2022-10-07 03:26:30' '2022-10-07 03:27:27' '2022-10-08 01:30:56' ...
 '2023-09-07 23:59:57' '2023-09-15 00:15:13' '2023-09-22 02:04:08']

Unique values for sampled_at:
['2022-09-24' '2022-10-01' '2022-10-08' ... '2022-12-29' '2024-04-01'
 '2021-05-04']

Unique values for created_at:
['2022-10-07 02:10:49' '2022-10-07 03:27:27' '2022-10-08 01:30:56' ...
 '2023-09-07 23:59:57' '2023-09-15 00:15:13' '2023-09-20 06:17:53']

Unique values for remark:
['Size 204\nP/H = 99 kg\nP/K = 2.020 kg\nSampling Anco'
 'Size 140\nADG = 0,31\nP/H = 139 kg\nP/K = 2.889 kg\nSampling anco'
 'Size 103\nADG = 0,38\nP/H = 160 kg\nP/K = 3.946 kg\nSampling anco' ...
 'Sampling ke 2' 'size 293' 'size 287']


In [45]:
# Descriptive Statistics
print("\nDescriptive Statistics:")
samplings.describe()




Descriptive Statistics:


cycle_id  average_weight            id
count  15032.000000    15032.000000  15032.000000
mean   19982.632052        9.900390  38925.218068
std     5742.703137        7.187137  13394.422325
min     3458.000000        0.010000   5308.000000
25%    16650.500000        4.490000  29964.750000
50%    20401.000000        8.130000  38806.500000
75%    24690.000000       13.772500  49932.250000
max    29874.000000      100.000000  61775.000000

In [46]:
# Check for Duplicate Rows
print("\nDuplicate Rows:")
samplings.duplicated().sum()


Duplicate Rows:


0

In [47]:
# Range Validation for Integer and Float Columns
numeric_columns = samplings.select_dtypes(include=['int64', 'float64']).columns
for column in numeric_columns:
    min_value = samplings[column].min()
    max_value = samplings[column].max()
    print(f"\nRange for {column}: {min_value} to {max_value}")




Range for cycle_id: 3458.0 to 29874.0

Range for average_weight: 0.01 to 100.0

Range for id: 5308.0 to 61775.0


In [48]:
# Foreign Key Validation
# Check if all 'cycle_id' values exist in the 'cycles' table
invalid_cycle_ids = samplings[~samplings['cycle_id'].isin(cycles['id'])]
print("\nInvalid 'cycle_id' values:")
print(invalid_cycle_ids)


Invalid 'cycle_id' values:
Empty DataFrame
Columns: [cycle_id, updated_at, sampled_at, created_at, average_weight, id, remark]
Index: []


1. **Basic Information:**
   - The dataset contains 15,032 entries with 7 columns.
   - Data types include 3 columns with `float64` and 4 columns with `object`.

2. **Missing Values:**
   - There are no missing values in most columns except for the `remark` column.
   - The `remark` column has 13,693 missing values out of 15,032, indicating it is largely incomplete.

3. **Descriptive Statistics:**
   - **cycle_id:** Ranges from 3,458 to 29,874 with a mean of approximately 19,982.
   - **average_weight:** Ranges from 0.01 to 100.00 with a mean of approximately 9.90.
   - **id:** Ranges from 5,308 to 61,775 with a mean of approximately 38,925.

4. **Duplicate Rows:**
   - There are no duplicate rows in the dataset.

### Key Points:
- The `remark` column has a significant amount of missing data (13,693 missing out of 15,032), which may require further investigation or imputation depending on its importance in the analysis.
- All other columns have complete data with no missing values.
- The data types and ranges for the numeric columns (`cycle_id`, `average_weight`, `id`) seem reasonable based on their descriptions.

This summary should provide a clear overview of the data quality and potential issues in the `samplings` table.